name: test files in github

on: workflow_dispatch

jobs:
    files:
        runs-on: ubuntu-latest
        steps:
         - name: create a file
           run: echo "Mani devops ..." > devops.txt
         - name: display the content of a file
           run: cat devops.txt
         - name: display the fies and dir
           run: ls -lrth
         - name: date
           run: date
         - name: system info
           run: uname  
         - name: calender month
           run: cat cal  